### PR TITLE
#33: Proposed logos, would appreciate some feedback

### PR DESCRIPTION
**Pull request by borgmatthew**

### CODE REVIEW

**Comment by KPull** [comment]
Hi, @borgmatthew! Thanks for your contribution. These all look great. I also like `bastion_text_with_castle`. I will leave this pull request open for a while until we get more feedback.

**Comment by borgmatthew** [comment]
Just added more flavors of `bastion_text_with_castle`, trying out different fonts. I've also tried out some effects with one of the fonts. Hope you like it :smile:

**Comment by tyrone-grech** [comment]
I think my favourite is bastion_orbitron.png

**Comment by KPull** [comment]
When you're ready to choose a design @borgmatthew, remove all the others and leave the one that you picked.

**Comment by KPull** [comment]
Ok, @borgmatthew! Could we also have a "small logo", with just the tower, please?  This will be used when we need to show an icon on the MVNRepository page for example.

**Comment by KPull** [comment]
Great job, @borgmatthew! I'm accepting the pull request. Thank you for your contribution and do keep an eye out for the logo on Bastion's GitHub landing page.

**Pull request merged**
